import{useMemo,useState}from'react';import{Clock3,Dumbbell,Armchair,BedDouble,PersonStanding,Sparkles}from'lucide-react';import{Duration,Log,Position,RunMode}from'./types';import{recommend}from'./recommend';const pos:{k:Position;t:string;icon:any}[]=[{k:'chair',t:'의자',icon:Armchair},{k:'bed',t:'침대',icon:BedDouble},{k:'floor',t:'바닥',icon:Dumbbell},{k:'standing',t:'서 있음',icon:PersonStanding}];const getLogs=():Log[]=>JSON.parse(localStorage.getItem('teum.logs')||'[]');
const API='https://hgiuigffkscvudohgvxf.supabase.co/rest/v1/workout_events';
const API_KEY='sb_publishable_mZZ45ZF5K4aN4Pc-WrwUuw_K4pcvqU7';
const getVisitorId=()=>{let id=localStorage.getItem('teum.visitorId');if(!id){id=crypto.randomUUID();localStorage.setItem('teum.visitorId',id)}return id};
async function sendWorkout(e:any,position:Position,run:RunMode){try{await fetch(API,{method:'POST',headers:{apikey:API_KEY,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({visitor_id:getVisitorId(),exercise_id:e.id,exercise_name:e.name,position,duration_seconds:e.seconds,run_mode:run,muscles:e.muscles,completed_at:new Date().toISOString()})})}catch{}}
export default function App(){const[logs,setLogs]=useState<Log[]>(getLogs);const[position,setPosition]=useState<Position>((localStorage.getItem('teum.position')as Position)||'chair');const[duration,setDuration]=useState<Duration>(60);const[run,setRun]=useState<RunMode>('none');const[showRecords,setShowRecords]=useState(false);const[textSize,setTextSize]=useState<'normal'|'large'|'xlarge'>(()=>{const v=localStorage.getItem('teum.textSize');return v==='large'||v==='xlarge'?v:(localStorage.getItem('teum.largeText')==='1'?'xlarge':'normal')});function cycleTextSize(){const v=textSize==='normal'?'large':textSize==='large'?'xlarge':'normal';setTextSize(v);localStorage.setItem('teum.textSize',v);localStorage.removeItem('teum.largeText')}const[current,setCurrent]=useState<ReturnType<typeof recommend>|null>(null);const[ticking,setTicking]=useState(false);const[left,setLeft]=useState(0);const today=logs.filter(l=>new Date(l.at).toDateString()===new Date().toDateString()).length;const week=logs.filter(l=>Date.now()-new Date(l.at).getTime()<7*864e5);const minutes=Math.round(week.reduce((a,b)=>a+b.seconds,0)/60);const muscles=useMemo(()=>{const o:Record<string,number>={};week.forEach(l=>l.muscles.forEach(m=>o[m]=(o[m]||0)+1));return o},[week]);function pick(lazy=false,d=duration){localStorage.setItem('teum.position',position);setCurrent(recommend(position,d,run,logs,lazy));}function start(){if(!current)return;setLeft(current.seconds);setTicking(true);const timer=setInterval(()=>setLeft(v=>{if(v<=1){clearInterval(timer);setTicking(false);return 0}return v-1}),1000)}function done(){if(!current)return;void sendWorkout(current,position,run);const n=[...logs,{exerciseId:current.id,at:new Date().toISOString(),seconds:current.seconds,muscles:current.muscles}];localStorage.setItem('teum.logs',JSON.stringify(n));setLogs(n);setCurrent(null);setTicking(false)}
if(showRecords){const totalSeconds=logs.reduce((a,b)=>a+b.seconds,0);const days=[...new Set(logs.map(l=>new Date(l.at).toLocaleDateString('ko-KR')))];const allMuscles:Record<string,number>={};logs.forEach(l=>l.muscles.forEach(m=>allMuscles[m]=(allMuscles[m]||0)+1));const recent=[...logs].reverse().slice(0,12);return <main className={`shell ${textSize==='large'?'largeText':textSize==='xlarge'?'xlargeText':''}`}><button className="back" onClick={()=>setShowRecords(false)}>← 홈으로</button><section className="recordHero"><small>나의 근육 저축</small><h1>{logs.length}번 움직였어요 🌱</h1><p>총 {Math.round(totalSeconds/60)}분 · 운동한 날 {days.length}일</p></section><section className="recordCard"><h2>이번 주</h2><div className="recordNumbers"><div><b>{week.length}</b><span>회</span></div><div><b>{minutes}</b><span>분</span></div><div><b>{Object.keys(muscles).length}</b><span>부위</span></div></div></section><section className="recordCard"><h2>내 몸에 쌓인 기록</h2>{['등','가슴·팔','코어','엉덩이','허벅지','종아리'].map(m=><div className="barrow" key={m}><span>{m}</span><i><em style={{width:Math.min(100,(allMuscles[m]||0)*10)+'%'}}/></i><small>{allMuscles[m]||0}</small></div>)}</section><section className="recordCard"><h2>최근 운동</h2>{recent.length?recent.map((l,i)=><div className="historyRow" key={l.at+i}><div><b>{l.muscles.join(' · ')}</b><small>{new Date(l.at).toLocaleDateString('ko-KR',{month:'short',day:'numeric'})}</small></div><strong>{l.seconds<60?l.seconds+'초':Math.round(l.seconds/60)+'분'}</strong></div>):<p className="emptyRecord">첫 운동을 완료하면 여기에 차곡차곡 쌓여요.</p>}</section></main>}
if(current)return <main className={`shell ${textSize==='large'?'largeText':textSize==='xlarge'?'xlargeText':''}`}><button className="back" onClick={()=>setCurrent(null)}>← 돌아가기</button><section className="work"><div className="pill">{current.muscles.join(' · ')}</div><h1>{current.name}</h1><EffectCard exerciseId={current.id} muscles={current.muscles}/><ExerciseGuide exerciseId={current.id} name={current.name}/><div className="dose">{current.dose}</div><p>{current.cue}</p>{ticking?<div className="timer">{left}초</div>:<button className="primary" onClick={start}>▶ 시작</button>}<button className="done" onClick={done}>✓ 완료했어요</button><small>통증, 어지럼증 또는 불편감이 생기면 중단하세요.</small></section></main>;
return <main className={`shell ${textSize==='large'?'largeText':textSize==='xlarge'?'xlargeText':''}`}><header><div><b>틈근육</b><span>지금 자세에서 시작하세요.</span></div><button className="textSize" onClick={cycleTextSize} aria-label="글씨 크기 변경"><span>가</span><b>{textSize==='normal'?'기본':textSize==='large'?'크게':'아주 크게'}</b></button></header><section className="hero"><p>오늘도 근육을 조금 저축해볼까요?</p><h1>{'🍪'.repeat(Math.min(today,5))}{'○'.repeat(Math.max(0,5-today))}</h1><strong>{today} / 5 스낵</strong><small>스낵은 움직임 실행 횟수예요. 못 채워도 괜찮아요.</small></section><button className="instant" onClick={()=>pick(false,60)}>🍪 지금 1분</button><section><h2>지금 어디에 있어요?</h2><div className="grid">{pos.map(p=>{const I=p.icon;return <button className={position===p.k?'selected':''} onClick={()=>setPosition(p.k)} key={p.k}><I size={22}/>{p.t}</button>})}</div></section><section><h2><Clock3 size={18}/> 몇 분 있어요?</h2><div className="times">{([30,60,180,300]as Duration[]).map(x=><button className={duration===x?'selected':''} onClick={()=>setDuration(x)} key={x}>{x===30?'30초':x/60+'분'}</button>)}</div></section><section><h2>오늘 몸은 어때요?</h2><select value={run} onChange={e=>setRun(e.target.value as RunMode)}><option value="none">🙂 보통</option><option value="easy">🏃 가벼운 러닝</option><option value="hard">🏃 강한 러닝</option><option value="long">🏁 장거리·대회</option><option value="recovery">🌿 장거리 다음날</option></select></section><button className="primary" onClick={()=>pick()}>운동 하나 뽑기</button><button className="lazy" onClick={()=>pick(true,60)}>🫠 진짜 아무것도 하기 싫어요</button><section className="stats"><div className="statsHead"><h2>이번 주 내 몸</h2><button onClick={()=>setShowRecords(true)}>내 기록 ›</button></div><p><b>{week.length}</b>회 · <b>{minutes}</b>분 저축</p>{['등','가슴·팔','코어','엉덩이','허벅지','종아리'].map(m=><div className="barrow" key={m}><span>{m}</span><i><em style={{width:Math.min(100,(muscles[m]||0)*20)+'%'}}/></i><small>{muscles[m]||0}</small></div>)}</section></main>}
type Guide={start:string;end:string;arrow:string;tip:string;avoid:string};
const guides:Record<string,Guide>={
c1:{start:'🪑🧍‍♀️  무릎 90°',end:'🪑🦵  다리 쭉',arrow:'무릎을 천천히 펴기 →',tip:'허벅지 앞쪽 힘을 느껴요',avoid:'반동으로 차올리지 않기'},
c2:{start:'🪑👣  두 발 바닥',end:'🪑⬆️🦵  한쪽 무릎',arrow:'좌우 번갈아 들어요 ↕',tip:'배에 살짝 힘을 줘요',avoid:'상체를 뒤로 젖히지 않기'},
c3:{start:'🪑  엉덩이 편하게',end:'🪑🍑✨  꽉 조이기',arrow:'5초 조였다 풀기 ↔',tip:'엉덩이 양쪽을 모아요',avoid:'허리를 과하게 꺾지 않기'},
c4:{start:'🪑  편하게 앉기',end:'🪑⭕  배 단단하게',arrow:'배꼽 주변을 부드럽게 조이기',tip:'숨은 계속 쉬어요',avoid:'숨 참지 않기'},
c5:{start:'🪑🦶  발바닥',end:'🪑🦶⬆️  뒤꿈치',arrow:'뒤꿈치를 위로 ↑',tip:'종아리를 천천히 조여요',avoid:'발가락으로 바닥을 밀지 않기'},
c6:{start:'🪑🦶  발바닥',end:'🪑⬆️👣  발끝',arrow:'발끝을 몸쪽으로 ↑',tip:'정강이 앞쪽을 느껴요',avoid:'무릎이 들리지 않게'},
c7:{start:'🪑🦵🦵  무릎 모음',end:'🪑🦵 ↔ 🦵',arrow:'무릎을 바깥으로 벌리기 ↔',tip:'엉덩이 옆쪽에 힘',avoid:'발이 따라 벌어지지 않게'},
c8:{start:'🤲  팔 앞쪽',end:'💪 ← 🤲 → 💪',arrow:'밴드를 양옆으로 벌리기 ↔',tip:'가슴은 편하게 열어요',avoid:'어깨를 으쓱하지 않기'},
c9:{start:'🪑🙆‍♀️  팔 W',end:'🪑💪⬅️➡️  팔꿈치 뒤로',arrow:'날개뼈를 뒤에서 모으기',tip:'어깨는 아래로 내려요',avoid:'허리를 꺾지 않기'},
c10:{start:'🪑🤲  팔 앞으로',end:'🪑💪  팔꿈치 뒤로',arrow:'팔꿈치를 몸통 옆으로 ←',tip:'등 가운데를 조여요',avoid:'어깨가 귀로 올라가지 않게'},
b1:{start:'🛏️ 누워 무릎 세우기',end:'🛏️ 🍑⬆️ 골반 들기',arrow:'골반을 천천히 ↑↓',tip:'엉덩이로 바닥을 밀어요',avoid:'허리를 과하게 꺾지 않기'},
b2:{start:'🛏️ 옆으로, 무릎 포개기',end:'🛏️ 🦪 무릎 열기',arrow:'발은 붙이고 위 무릎만 ↑',tip:'엉덩이 옆쪽을 느껴요',avoid:'골반이 뒤로 넘어가지 않게'},
b3:{start:'🛏️ 옆으로 다리 포개기',end:'🛏️ 🦵⬆️ 위 다리 들기',arrow:'위 다리를 곧게 ↑',tip:'발끝은 정면을 봐요',avoid:'다리를 앞쪽으로 보내지 않기'},
b4:{start:'🛏️ 편하게 눕기',end:'🛏️ 🍑✨ 조이기',arrow:'5초 조였다 풀기',tip:'양쪽 엉덩이를 같이 조여요',avoid:'허리에 힘 몰지 않기'},
b5:{start:'🛏️ 누워 편하게',end:'🛏️ ⭕ 배 단단하게',arrow:'배 주변을 살짝 조이기',tip:'자연스럽게 호흡해요',avoid:'숨 참지 않기'},
b6:{start:'🛏️ 무릎 세우기',end:'🛏️ 🦵➡️ 발 미끄러뜨리기',arrow:'한쪽 발을 천천히 멀리 →',tip:'허리는 편안하게',avoid:'허리가 뜨지 않게'},
b7:{start:'🛏️ 🤲 팔 위',end:'🛏️ 💪↔️💪',arrow:'밴드를 양옆으로 벌리기',tip:'등과 어깨 뒤쪽을 느껴요',avoid:'목에 힘주지 않기'},
f1:{start:'🧘‍♀️ 팔다리 위로',end:'🧘‍♀️ ↙️팔·반대다리↘️',arrow:'반대 팔·다리 천천히 내리기',tip:'허리를 바닥에 가볍게 붙여요',avoid:'허리가 뜨지 않게'},
f2:{start:'🐾 네발 기기',end:'🦸 팔·반대다리 쭉',arrow:'대각선으로 길게 뻗기 ↗',tip:'몸통은 흔들리지 않게',avoid:'허리를 꺾지 않기'},
f3:{start:'🧎‍♀️ 손·무릎 바닥',end:'🧎‍♀️⬇️ 가슴 낮추기',arrow:'팔꿈치를 굽혔다 펴기',tip:'머리부터 무릎까지 길게',avoid:'허리가 먼저 꺼지지 않게'},
f4:{start:'🧘 옆으로 다리 포개기',end:'🧘 🦵⬆️ 위 다리',arrow:'위 다리를 천천히 ↑↓',tip:'골반을 수직으로 유지',avoid:'몸통이 뒤로 넘어가지 않게'},
s1:{start:'🧍 두 발 바닥',end:'🧍⬆️ 뒤꿈치 들기',arrow:'까치발로 천천히 ↑↓',tip:'벽이나 의자를 잡아도 돼요',avoid:'발목이 바깥으로 꺾이지 않게'},
s2:{start:'🧍🪑 의자 앞',end:'🏋️‍♀️⬇️ 엉덩이 뒤로',arrow:'의자에 앉듯 내려가기',tip:'엉덩이를 뒤로 보내요',avoid:'무릎이 안쪽으로 모이지 않게'},
s3:{start:'🧍🤲🧱 벽 짚기',end:'🧍➡️🧱 몸 가까이',arrow:'팔꿈치를 굽혔다 밀기',tip:'몸을 한 줄로 유지',avoid:'허리가 꺾이지 않게'},
s4:{start:'🧍🤲 책상 짚기',end:'🧍↘️ 가슴 낮추기',arrow:'가슴을 책상 쪽으로 ↘',tip:'몸 전체가 함께 움직여요',avoid:'어깨를 으쓱하지 않기'},
s5:{start:'🧍 두 발 서기',end:'🧍 🦵⬅️ 다리 뒤로',arrow:'한쪽 다리를 뒤로 ←',tip:'엉덩이를 조여요',avoid:'허리를 젖히지 않기'},
s6:{start:'🧍 두 발 서기',end:'🧍🦵➡️ 다리 옆으로',arrow:'한쪽 다리를 옆으로 →',tip:'발끝은 정면',avoid:'몸통을 반대로 기울이지 않기'},
s7:{start:'🧱🙆‍♀️ 팔 W',end:'🧱⬆️ 팔 위로',arrow:'벽을 따라 팔을 위아래로',tip:'어깨는 귀에서 멀리',avoid:'허리가 벽에서 과하게 뜨지 않게'},
s8:{start:'🧍 어깨 편하게',end:'🧍✨ 날개뼈 모음',arrow:'어깨를 뒤·아래로 살짝',tip:'가슴을 과하게 내밀지 않아요',avoid:'어깨를 으쓱하지 않기'}
};
function ExerciseGuide({exerciseId,name}:{exerciseId:string;name:string}){const g=guides[exerciseId]||{start:'시작 자세',end:'끝 자세',arrow:'천천히 움직이기',tip:'편안한 범위에서 움직여요',avoid:'통증이 나면 중단'};return <div className="guide"><div className="guideTitle">👀 2초 동작 설명</div><div className="guideFrames"><div className="guideFrame"><small>① 시작</small><strong>{g.start}</strong></div><div className="guideArrow">→</div><div className="guideFrame"><small>② 움직임</small><strong>{g.end}</strong></div></div><div className="guideMove">↳ {g.arrow}</div><div className="guideTip">✨ {g.tip}</div><div className="guideAvoid">× {g.avoid}</div></div>}
const effects:Record<string,{headline:string;now:string;later:string}>={
c1:{headline:"🦵 계단과 일어나기를 받치는 허벅지 힘",now:"허벅지 앞쪽 근육을 사용해요.",later:"꾸준히 하면 무릎을 펴는 힘과 앉았다 일어나기·계단 오르기를 받치는 하체 근력에 도움이 돼요."},
c2:{headline:"🚶 다리를 들어 올리는 힘",now:"고관절과 복부 주변 근육을 사용해요.",later:"꾸준히 하면 걷기와 계단에서 다리를 들어 올리는 움직임을 받치는 데 도움이 돼요."},
c3:{headline:"🍑 앉아서도 엉덩이 깨우기",now:"엉덩이 근육을 직접 수축해요.",later:"반복하면 엉덩이에 힘을 주는 감각과 근육 사용량을 쌓는 데 도움이 돼요."},
c4:{headline:"⭕ 몸통을 버티는 코어 힘",now:"복부 주변에 힘을 주며 몸통을 안정시켜요.",later:"꾸준히 하면 일상에서 몸통을 지지하는 코어 근력에 도움이 돼요."},
c5:{headline:"🦶 걷고 뛰는 힘을 받치는 종아리",now:"종아리 근육을 수축해요.",later:"꾸준히 하면 걷기·달리기·계단에서 발목을 밀어내는 힘을 기르는 데 도움이 돼요."},
c6:{headline:"👣 발끝을 드는 정강이 힘",now:"정강이 앞쪽 근육을 사용해요.",later:"꾸준히 하면 발끝을 들어 올리는 힘과 발목 주변 근력 유지에 도움이 돼요."},
c7:{headline:"🍑 골반을 지지하는 엉덩이 옆 힘",now:"엉덩이 옆쪽 근육을 사용해요.",later:"꾸준히 하면 걷거나 한 발로 설 때 골반을 지지하는 근력에 도움이 돼요."},
c8:{headline:"💪 등·어깨 뒤쪽을 쓰는 당기기",now:"등 위쪽과 어깨 뒤쪽 근육을 사용해요.",later:"꾸준히 하면 상체를 지지하고 팔을 뒤로 당기는 근력에 도움이 돼요."},
c9:{headline:"🪽 날개뼈 주변을 깨우는 1분",now:"등 위쪽과 날개뼈 주변 근육을 사용해요.",later:"꾸준히 하면 상체를 지지하는 등·어깨 근력과 자세 유지 능력에 도움이 돼요."},
c10:{headline:"🧲 등을 당기는 힘",now:"등 가운데와 팔을 당기는 근육을 사용해요.",later:"꾸준히 하면 당기기 동작과 상체 지지에 필요한 등 근력에 도움이 돼요."},
b1:{headline:"🍑 엉덩이와 고관절을 튼튼하게",now:"엉덩이와 허벅지 뒤쪽을 사용해 골반을 들어요.",later:"꾸준히 하면 엉덩이·고관절 주변 근력과 하체 움직임을 받치는 힘에 도움이 돼요."},
b2:{headline:"🦪 골반 옆을 지지하는 엉덩이 힘",now:"엉덩이 옆쪽 근육을 집중해서 사용해요.",later:"꾸준히 하면 걷기·달리기에서 골반과 허벅지를 안정적으로 지지하는 근력에 도움이 돼요."},
b3:{headline:"🍑 엉덩이 옆쪽을 탄탄하게",now:"다리를 옆으로 드는 엉덩이 근육을 사용해요.",later:"꾸준히 하면 한 발 지지와 옆 방향 움직임을 받치는 엉덩이 근력에 도움이 돼요."},
b4:{headline:"🍑 누운 채로 엉덩이 깨우기",now:"누운 자세에서 엉덩이 근육을 직접 수축해요.",later:"반복하면 엉덩이에 힘을 주는 감각을 익히고 다음 하체 운동에서 엉덩이를 쓰는 데 도움이 돼요."},
b5:{headline:"⭕ 누워서 만드는 코어 지지력",now:"호흡을 유지하며 복부 주변을 단단하게 만들어요.",later:"꾸준히 하면 움직일 때 몸통을 안정시키는 코어 근력에 도움이 돼요."},
b6:{headline:"🧩 다리를 움직여도 몸통은 안정적으로",now:"다리를 움직이는 동안 복부와 골반 주변을 사용해요.",later:"꾸준히 하면 팔다리를 움직일 때 몸통을 안정시키는 능력에 도움이 돼요."},
b7:{headline:"🪽 누워서 등·어깨 뒤쪽 깨우기",now:"밴드를 벌리며 등 위쪽과 어깨 뒤쪽을 사용해요.",later:"꾸준히 하면 상체를 지지하고 팔을 벌리는 등·어깨 근력에 도움이 돼요."},
f1:{headline:"🐞 팔·다리가 움직여도 단단한 코어",now:"반대 팔과 다리를 움직이며 복부로 몸통을 잡아요.",later:"꾸준히 하면 팔다리 움직임 중 몸통을 안정시키는 코어 근력에 도움이 돼요."},
f2:{headline:"🐾 코어와 엉덩이를 함께",now:"코어와 엉덩이로 몸통의 흔들림을 제어해요.",later:"꾸준히 하면 몸통 안정성과 엉덩이 근력을 함께 기르는 데 도움이 돼요."},
f3:{headline:"💪 가슴·팔로 몸을 미는 힘",now:"가슴과 팔 뒤쪽 근육을 사용해 몸을 밀어요.",later:"꾸준히 하면 밀기 동작에 필요한 상체 근력을 기르는 데 도움이 돼요."},
f4:{headline:"🍑 옆 엉덩이 근력 쌓기",now:"엉덩이 옆쪽을 사용해 다리를 들어요.",later:"꾸준히 하면 골반을 지지하고 옆 방향 움직임을 받치는 근력에 도움이 돼요."},
s1:{headline:"🦶 걷기와 달리기의 마지막 밀어내기",now:"체중을 지지하며 종아리 근육을 사용해요.",later:"꾸준히 하면 걷기·달리기·계단에서 발목을 밀어내는 종아리 근력에 도움이 돼요."},
s2:{headline:"🪑 일어나고 앉는 하체 힘",now:"허벅지와 엉덩이를 함께 사용해요.",later:"꾸준히 하면 의자에서 일어나기와 계단 같은 일상 동작을 받치는 하체 근력에 도움이 돼요."},
s3:{headline:"🧱 부담 낮게 시작하는 미는 힘",now:"가슴·어깨·팔을 사용해 벽을 밀어요.",later:"꾸준히 하면 일상적인 밀기 동작에 필요한 상체 근력을 기르는 데 도움이 돼요."},
s4:{headline:"💪 한 단계 더 강한 상체 밀기",now:"가슴·어깨·팔과 몸통을 함께 사용해요.",later:"꾸준히 하면 푸시업으로 이어지는 상체 밀기 근력과 몸통 지지력에 도움이 돼요."},
s5:{headline:"🍑 뒤로 차는 엉덩이 힘",now:"다리를 뒤로 보내며 엉덩이 근육을 사용해요.",later:"꾸준히 하면 걷기·달리기에서 다리를 뒤로 미는 고관절 근력에 도움이 돼요."},
s6:{headline:"🍑 옆으로 버티는 엉덩이 힘",now:"다리를 옆으로 들며 엉덩이 옆쪽을 사용해요.",later:"꾸준히 하면 한 발로 설 때 골반을 지지하는 근력에 도움이 돼요."},
s7:{headline:"🪽 벽에서 만드는 등·어깨 지지력",now:"등 위쪽과 어깨 주변을 사용하며 팔을 움직여요.",later:"꾸준히 하면 팔을 올릴 때 필요한 어깨 주변 근력과 상체 자세 유지에 도움이 돼요."},
s8:{headline:"🪽 굳은 상체에 작은 리셋",now:"날개뼈 주변과 등 위쪽 근육을 가볍게 수축해요.",later:"꾸준히 하면 상체를 지지하는 등 근력과 어깨 위치를 유지하는 능력에 도움이 돼요."}
};
function EffectCard({exerciseId,muscles}:{exerciseId:string;muscles:string[]}){const e=effects[exerciseId]||{headline:"🌱 오늘의 작은 근력 저축",now:`${muscles.join(" · ")} 근육을 짧게 사용해요.`,later:"꾸준히 반복하고 조금씩 강도를 높이면 해당 부위의 근력을 기르는 데 도움이 돼요."};return <div className="effectCard"><div className="effectTitle">💡 이 운동의 효과</div><h3>{e.headline}</h3><div><small>쓰는 곳</small><p>{e.now}</p></div><div><small>꾸준히 하면</small><p>{e.later}</p></div></div>}