import{useMemo,useState}from'react';import{Clock3,Dumbbell,Armchair,BedDouble,PersonStanding,Sparkles}from'lucide-react';import{Duration,Log,Position,RunMode}from'./types';import{recommend}from'./recommend';const pos:{k:Position;t:string;icon:any}[]=[{k:'chair',t:'의자',icon:Armchair},{k:'bed',t:'침대',icon:BedDouble},{k:'floor',t:'바닥',icon:Dumbbell},{k:'standing',t:'서 있음',icon:PersonStanding}];const getLogs=():Log[]=>JSON.parse(localStorage.getItem('teum.logs')||'[]');
export default function App(){const[logs,setLogs]=useState<Log[]>(getLogs);const[position,setPosition]=useState<Position>((localStorage.getItem('teum.position')as Position)||'chair');const[duration,setDuration]=useState<Duration>(60);const[run,setRun]=useState<RunMode>('none');const[current,setCurrent]=useState<ReturnType<typeof recommend>|null>(null);const[ticking,setTicking]=useState(false);const[left,setLeft]=useState(0);const today=logs.filter(l=>new Date(l.at).toDateString()===new Date().toDateString()).length;const week=logs.filter(l=>Date.now()-new Date(l.at).getTime()<7*864e5);const minutes=Math.round(week.reduce((a,b)=>a+b.seconds,0)/60);const muscles=useMemo(()=>{const o:Record<string,number>={};week.forEach(l=>l.muscles.forEach(m=>o[m]=(o[m]||0)+1));return o},[week]);function pick(lazy=false,d=duration){localStorage.setItem('teum.position',position);setCurrent(recommend(position,d,run,logs,lazy));}function start(){if(!current)return;setLeft(current.seconds);setTicking(true);const timer=setInterval(()=>setLeft(v=>{if(v<=1){clearInterval(timer);setTicking(false);return 0}return v-1}),1000)}function done(){if(!current)return;const n=[...logs,{exerciseId:current.id,at:new Date().toISOString(),seconds:current.seconds,muscles:current.muscles}];localStorage.setItem('teum.logs',JSON.stringify(n));setLogs(n);setCurrent(null);setTicking(false)}
if(current)return <main className="shell"><button className="back" onClick={()=>setCurrent(null)}>← 돌아가기</button><section className="work"><div className="pill">{current.muscles.join(' · ')}</div><h1>{current.name}</h1><MoveMap exerciseId={current.id} name={current.name}/><div className="dose">{current.dose}</div><p>{current.cue}</p>{ticking?<div className="timer">{left}초</div>:<button className="primary" onClick={start}>▶ 시작</button>}<button className="done" onClick={done}>✓ 완료했어요</button><small>통증, 어지럼증 또는 불편감이 생기면 중단하세요.</small></section></main>;
return <main className="shell"><header><div><b>틈근육</b><span>지금 자세에서 시작하세요.</span></div><Sparkles/></header><section className="hero"><p>오늘도 근육을 조금 저축해볼까요?</p><h1>{'🍪'.repeat(Math.min(today,5))}{'○'.repeat(Math.max(0,5-today))}</h1><strong>{today} / 5 스낵</strong><small>스낵은 움직임 실행 횟수예요. 못 채워도 괜찮아요.</small></section><button className="instant" onClick={()=>pick(false,60)}>🍪 지금 1분</button><section><h2>지금 어디에 있어요?</h2><div className="grid">{pos.map(p=>{const I=p.icon;return <button className={position===p.k?'selected':''} onClick={()=>setPosition(p.k)} key={p.k}><I size={22}/>{p.t}</button>})}</div></section><section><h2><Clock3 size={18}/> 몇 분 있어요?</h2><div className="times">{([30,60,180,300]as Duration[]).map(x=><button className={duration===x?'selected':''} onClick={()=>setDuration(x)} key={x}>{x===30?'30초':x/60+'분'}</button>)}</div></section><section><h2>오늘 몸은 어때요?</h2><select value={run} onChange={e=>setRun(e.target.value as RunMode)}><option value="none">🙂 보통</option><option value="easy">🏃 가벼운 러닝</option><option value="hard">🏃 강한 러닝</option><option value="long">🏁 장거리·대회</option><option value="recovery">🌿 장거리 다음날</option></select></section><button className="primary" onClick={()=>pick()}>운동 하나 뽑기</button><button className="lazy" onClick={()=>pick(true,60)}>🫠 진짜 아무것도 하기 싫어요</button><section className="stats"><h2>이번 주 내 몸</h2><p><b>{week.length}</b>회 · <b>{minutes}</b>분 저축</p>{['등','가슴·팔','코어','엉덩이','허벅지','종아리'].map(m=><div className="barrow" key={m}><span>{m}</span><i><em style={{width:Math.min(100,(muscles[m]||0)*20)+'%'}}/></i><small>{muscles[m]||0}</small></div>)}</section></main>}
type Guide={start:string;end:string;arrow:string;tip:string;avoid:string};
const guides:Record<string,Guide>={
c1:{start:'🪑🧍‍♀️  무릎 90°',end:'🪑🦵  다리 쭉',arrow:'무릎을 천천히 펴기 →',tip:'허벅지 앞쪽 힘을 느껴요',avoid:'반동으로 차올리지 않기'},
c2:{start:'🪑👣  두 발 바닥',end:'🪑⬆️🦵  한쪽 무릎',arrow:'좌우 번갈아 들어요 ↕',tip:'배에 살짝 힘을 줘요',avoid:'상체를 뒤로 젖히지 않기'},
c3:{start:'🪑  엉덩이 편하게',end:'🪑🍑✨  꽉 조이기',arrow:'5초 조였다 풀기 ↔',tip:'엉덩이 양쪽을 모아요',avoid:'허리를 과하게 꺾지 않기'},
c4:{start:'🪑  편하게 앉기',end:'🪑⭕  배 단단하게',arrow:'배꼽 주변을 부드럽게 조이기',tip:'숨은 계속 쉬어요',avoid:'숨 참지 않기'},
c5:{start:'🪑🦶  발바닥',end:'🪑🦶⬆️  뒤꿈치',arrow:'뒤꿈치를 위로 ↑',tip:'종아리를 천천히 조여요',avoid:'발가락으로 바닥을 밀지 않기'},
c6:{start:'🪑🦶  발바닥',end:'🪑⬆️👣  발끝',arrow:'발끝을 몸쪽으로 ↑',tip:'정강이 앞쪽을 느껴요',avoid:'무릎이 들리지 않게'},
c7:{start:'🪑🦵🦵  무릎 모음',end:'🪑🦵 ↔ 🦵',arrow:'무릎을 바깥으로 벌리기 ↔',tip:'엉덩이 옆쪽에 힘',avoid:'발이 따라 벌어지지 않게'},
c8:{start:'🤲  팔 앞쪽',end:'💪 ← 🤲 → 💪',arrow:'밴드를 양옆으로 벌리기 ↔',tip:'가슴은 편하게 열어요',avoid:'어깨를 으쓱하지 않기'},
c9:{start:'🪑🙆‍♀️  팔 W',end:'🪑💪⬅️➡️  팔꿈치 뒤로',arrow:'날개뼈를 뒤에서 모으기',tip:'어깨는 아래로 내려요',avoid:'허리를 꺾지 않기'},
c10:{start:'🪑🤲  팔 앞으로',end:'🪑💪  팔꿈치 뒤로',arrow:'팔꿈치를 몸통 옆으로 ←',tip:'등 가운데를 조여요',avoid:'어깨가 귀로 올라가지 않게'},
b1:{start:'🛏️ 누워 무릎 세우기',end:'🛏️ 🍑⬆️ 골반 들기',arrow:'골반을 천천히 ↑↓',tip:'엉덩이로 바닥을 밀어요',avoid:'허리를 과하게 꺾지 않기'},
b2:{start:'🛏️ 옆으로, 무릎 포개기',end:'🛏️ 🦪 무릎 열기',arrow:'발은 붙이고 위 무릎만 ↑',tip:'엉덩이 옆쪽을 느껴요',avoid:'골반이 뒤로 넘어가지 않게'},
b3:{start:'🛏️ 옆으로 다리 포개기',end:'🛏️ 🦵⬆️ 위 다리 들기',arrow:'위 다리를 곧게 ↑',tip:'발끝은 정면을 봐요',avoid:'다리를 앞쪽으로 보내지 않기'},
b4:{start:'🛏️ 편하게 눕기',end:'🛏️ 🍑✨ 조이기',arrow:'5초 조였다 풀기',tip:'양쪽 엉덩이를 같이 조여요',avoid:'허리에 힘 몰지 않기'},
b5:{start:'🛏️ 누워 편하게',end:'🛏️ ⭕ 배 단단하게',arrow:'배 주변을 살짝 조이기',tip:'자연스럽게 호흡해요',avoid:'숨 참지 않기'},
b6:{start:'🛏️ 무릎 세우기',end:'🛏️ 🦵➡️ 발 미끄러뜨리기',arrow:'한쪽 발을 천천히 멀리 →',tip:'허리는 편안하게',avoid:'허리가 뜨지 않게'},
b7:{start:'🛏️ 🤲 팔 위',end:'🛏️ 💪↔️💪',arrow:'밴드를 양옆으로 벌리기',tip:'등과 어깨 뒤쪽을 느껴요',avoid:'목에 힘주지 않기'},
f1:{start:'🧘‍♀️ 팔다리 위로',end:'🧘‍♀️ ↙️팔·반대다리↘️',arrow:'반대 팔·다리 천천히 내리기',tip:'허리를 바닥에 가볍게 붙여요',avoid:'허리가 뜨지 않게'},
f2:{start:'🐾 네발 기기',end:'🦸 팔·반대다리 쭉',arrow:'대각선으로 길게 뻗기 ↗',tip:'몸통은 흔들리지 않게',avoid:'허리를 꺾지 않기'},
f3:{start:'🧎‍♀️ 손·무릎 바닥',end:'🧎‍♀️⬇️ 가슴 낮추기',arrow:'팔꿈치를 굽혔다 펴기',tip:'머리부터 무릎까지 길게',avoid:'허리가 먼저 꺼지지 않게'},
f4:{start:'🧘 옆으로 다리 포개기',end:'🧘 🦵⬆️ 위 다리',arrow:'위 다리를 천천히 ↑↓',tip:'골반을 수직으로 유지',avoid:'몸통이 뒤로 넘어가지 않게'},
s1:{start:'🧍 두 발 바닥',end:'🧍⬆️ 뒤꿈치 들기',arrow:'까치발로 천천히 ↑↓',tip:'벽이나 의자를 잡아도 돼요',avoid:'발목이 바깥으로 꺾이지 않게'},
s2:{start:'🧍🪑 의자 앞',end:'🏋️‍♀️⬇️ 엉덩이 뒤로',arrow:'의자에 앉듯 내려가기',tip:'엉덩이를 뒤로 보내요',avoid:'무릎이 안쪽으로 모이지 않게'},
s3:{start:'🧍🤲🧱 벽 짚기',end:'🧍➡️🧱 몸 가까이',arrow:'팔꿈치를 굽혔다 밀기',tip:'몸을 한 줄로 유지',avoid:'허리가 꺾이지 않게'},
s4:{start:'🧍🤲 책상 짚기',end:'🧍↘️ 가슴 낮추기',arrow:'가슴을 책상 쪽으로 ↘',tip:'몸 전체가 함께 움직여요',avoid:'어깨를 으쓱하지 않기'},
s5:{start:'🧍 두 발 서기',end:'🧍 🦵⬅️ 다리 뒤로',arrow:'한쪽 다리를 뒤로 ←',tip:'엉덩이를 조여요',avoid:'허리를 젖히지 않기'},
s6:{start:'🧍 두 발 서기',end:'🧍🦵➡️ 다리 옆으로',arrow:'한쪽 다리를 옆으로 →',tip:'발끝은 정면',avoid:'몸통을 반대로 기울이지 않기'},
s7:{start:'🧱🙆‍♀️ 팔 W',end:'🧱⬆️ 팔 위로',arrow:'벽을 따라 팔을 위아래로',tip:'어깨는 귀에서 멀리',avoid:'허리가 벽에서 과하게 뜨지 않게'},
s8:{start:'🧍 어깨 편하게',end:'🧍✨ 날개뼈 모음',arrow:'어깨를 뒤·아래로 살짝',tip:'가슴을 과하게 내밀지 않아요',avoid:'어깨를 으쓱하지 않기'}
};
function ExerciseGuide({exerciseId,name}:{exerciseId:string;name:string}){const g=guides[exerciseId]||{start:'시작 자세',end:'끝 자세',arrow:'천천히 움직이기',tip:'편안한 범위에서 움직여요',avoid:'통증이 나면 중단'};return <div className="guide"><div className="guideTitle">👀 2초 동작 설명</div><div className="guideFrames"><div className="guideFrame"><small>① 시작</small><strong>{g.start}</strong></div><div className="guideArrow">→</div><div className="guideFrame"><small>② 움직임</small><strong>{g.end}</strong></div></div><div className="guideMove">↳ {g.arrow}</div><div className="guideTip">✨ {g.tip}</div><div className="guideAvoid">× {g.avoid}</div></div>}
function Figure({pose}:{pose:'sitStart'|'sitLeg'|'wStart'|'wEnd'|'bridgeStart'|'bridgeEnd'}){const leg=pose==='sitLeg', w=pose==='wStart'||pose==='wEnd', bridge=pose==='bridgeStart'||pose==='bridgeEnd', end=pose==='wEnd'||pose==='bridgeEnd';return <svg className="bodyMap" viewBox="0 0 150 150" aria-hidden="true">{bridge?<><line className="fixed" x1="18" y1="118" x2="132" y2="118"/><circle className="fixedFill" cx="30" cy={end?88:103} r="9"/><line className="fixed" x1="39" y1={end?91:104} x2="72" y2={end?82:106}/><line className="moving" x1="72" y1={end?82:106} x2="103" y2="105"/><line className="fixed" x1="103" y1="105" x2="122" y2="118"/><ellipse className="target" cx="70" cy={end?83:105} rx="13" ry="8"/>{end&&<path className="motionPath" d="M68 104 Q70 91 72 80"/>}</>:<><rect className="prop" x="34" y="88" width="56" height="7" rx="3"/><line className="prop" x1="40" y1="95" x2="37" y2="137"/><line className="prop" x1="84" y1="95" x2="90" y2="137"/><circle className="fixedFill" cx="65" cy="32" r="10"/><line className="fixed" x1="65" y1="42" x2="65" y2="88"/>{w?<><line className="moving" x1="64" y1="55" x2={end?45:38} y2={end?62:50}/><line className="moving" x1={end?45:38} y1={end?62:50} x2={end?42:28} y2={end?42:32}/><line className="moving" x1="66" y1="55" x2={end?85:92} y2={end?62:50}/><line className="moving" x1={end?85:92} y1={end?62:50} x2={end?88:102} y2={end?42:32}/><ellipse className="target" cx="65" cy="61" rx="17" ry="12"/>{end&&<><path className="motionPath" d="M31 51 Q39 58 47 61"/><path className="motionPath" d="M99 51 Q91 58 83 61"/></>}</>:<><line className="fixed" x1="65" y1="88" x2="92" y2="91"/><line className="moving" x1="92" y1="91" x2={leg?128:94} y2={leg?91:128}/><ellipse className="target" cx="84" cy="89" rx="15" ry="8"/>{leg&&<path className="motionPath" d="M99 118 Q119 108 128 93"/>}</>}</>}</svg>}
function MoveMap({exerciseId,name}:{exerciseId:string;name:string}){const map:any={c1:{a:'sitStart',b:'sitLeg',c1:'허벅지 고정',c2:'무릎만 천천히'},c9:{a:'wStart',b:'wEnd',c1:'어깨는 아래로',c2:'날개뼈만 모으기'},b1:{a:'bridgeStart',b:'bridgeEnd',c1:'발은 바닥에',c2:'엉덩이로 들어요'}};const m=map[exerciseId];if(!m)return <ExerciseGuide exerciseId={exerciseId} name={name}/>;return <div className="moveMap"><div className="mapHead"><b>동작 한눈에 보기</b><span>연두 = 힘을 느낄 곳</span></div><div className="mapFrames"><div><small>① 시작</small><Figure pose={m.a}/></div><div><small>② 여기까지</small><Figure pose={m.b}/></div></div><div className="mapCues"><b>● {m.c1}</b><b>● {m.c2}</b></div></div>}